/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hw;

import org.junit.Test;

import junit.framework.Assert;

import static org.junit.Assert.*;

import java.util.HashSet;

public class AppTest {
    @Test public void test_if_indic() {
        App testin_dic = new App();
        HashSet<String> tt = new HashSet<String>();
        tt.add("11");
        tt.add("22");
        boolean ret = App.if_indic("s", tt);
        Assert.assertEquals(false, ret);
    }

    @Test public void testRep(){
        App testReplace = new App();
        String res = App.rep("qwerty", 2, '1');
        Assert.assertEquals("qw1rty", res);

    }
        
    
}
